# AIML Internship - Week 1 Assignment
## Task 1: Student Performance Dataset Analysis
### Objective
To clean, preprocess, and analyze a student performance dataset containing
missing values, duplicate records, inconsistent labels, datatype issues,
and unclear columns.
### Author: Trapti Jain

##1)Load Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv("1_student_performance_raw_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

##2)Preview Dataset

In [2]:
df.head()

,Student ID,Gender,Age,Hours_Studied,Attendance,Assignment Score,Final Exam Score,Parental involvement,Competency Areas,Internet Access,...,Previous_Scores,Motivation_Level,Tutoring_Sessions,Teacher_Quality,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Notes
0,S00001,M,18.0,15.6,NaN,77.0,47,Low,AI,N,...,83.0,Low,11.0,Excellent,Positive,10.0,NaN,High School,13.2,NaN
1,2,Male,21.0,7.5,NaN,36.0,85,Low,AI,No,...,NaN,Low,5.0,good,positive,7.0,yes,Master,NaN,NaN
2,S00003,M,20.0,8.7,68%,64.0,98,medium,Web Dev,Yes,...,NaN,high,NaN,Excellent,neutral,5.0,N,High School,NaN,check
3,S00004,M,21.0,NaN,76%,55.0,48,low,Data Analysis,N,...,NaN,Low,6.0,Good,neutral,5.0,no,Bachelor,24.2,-
4,5,F,17.0,NaN,NaN,73.0,50,NaN,Cyber Security,no,...,NaN,Low,NaN,Good,Neutral,4.0,Yes,bachelor,2.9,OK

In [3]:
df.tail()

,Student ID,Gender,Age,Hours_Studied,Attendance,Assignment Score,Final Exam Score,Parental involvement,Competency Areas,Internet Access,...,Previous_Scores,Motivation_Level,Tutoring_Sessions,Teacher_Quality,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Notes
5795,2061,Female,21.0,6.2,59%,NaN,63,Low,Data Analysis,No,...,77.0,High,1.0,Poor,positive,1.0,no,bachelor,28.6,OK
5796,STU-2907,Male,20.0,12.3,78%,95.0,38,NaN,Web Dev,NaN,...,NaN,high,10.0,good,Negative,NaN,no,High School,26.1,-
5797,S05396,F,20.0,3.8,57%,68.0,94,medium,Cyber Security,NaN,...,87.0,High,0.0,Poor,Positive,NaN,yes,High School,22.2,NaN
5798,3369,Male,19.0,16.3,NaN,NaN,84,Medium,Web Dev,Y,...,NaN,high,10.0,Excellent,Negative,1.0,Yes,PhD,17.3,NaN
5799,S00240,Female,24.0,6.4,54,83.0,44,low,Cyber Security,no,...,NaN,high,1.0,Poor,Neutral,NaN,Yes,Bachelor,0.9,check

##3)Dataset Shape

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 5800
Columns: 23

Dataset contains approximately 5800 rows and 23 columns.

##4) Inspecting data types

In [5]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5800 entries, 0 to 5799
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student ID                  5800 non-null   object
 1   Gender                      5800 non-null   object
 2   Age                         5323 non-null   float64
 3   Hours_Studied               3897 non-null   float64
 4   Attendance                  3916 non-null   object
 5   Assignment Score            3850 non-null   float64
 6   Final Exam Score            5800 non-null   int64
 7   Parental involvement        4984 non-null   object
 8   Competency Areas            5800 non-null   object
 9   Internet Access             4958 non-null   object
 10  Access_to_Resources         5800 non-null   object
 11  Extracurricular_Activities  5800 non-null   object
 12  Sleep_Hours                 3863 non-null   float64
 13  Previous_Scores             3861 non-null   float64
 14  Motivation_Level            5800 non-null   object
 15  Tutoring_Sessions           3855 non-null   float64
 16  Teacher_Quality             5800 non-null   object
 17  Peer_Influence              5800 non-null   object
 18  Physical_Activity           3857 non-null   float64
 19  Learning_Disabilities       4972 non-null   object
 20  Parental_Education_Level    5800 non-null   object
 21  Distance_from_Home          3837 non-null   float64
 22  Notes                       4322 non-null   object
dtypes: float64(8), int64(1), object(14)
memory usage: 1.0+ MB

The dataset contains a mix of numerical and categorical features. Some columns have missing values, and the Attendance column requires datatype conversion. Therefore, data cleaning and preprocessing are necessary before analysis.

## 5) Feature Understanding Table

In [6]:
# Feature Understanding Table
feature_table = pd.DataFrame({
    "Feature Type": [
        "Identifier",
        "Numerical",
        "Categorical",
        "Unclear Column",
        "Target Variable"
    ],

    "Columns": [
        "Student ID",
        "Age, Hours_Studied, Attendance, Assignment Score, Final Exam Score, Sleep_Hours, Previous_Scores, Tutoring_Sessions, Physical_Activity, Distance_from_Home",
        "Gender, Parental_Involvement, Competency_Areas, Internet_Access, Access_to_Resources, Extracurricular_Activities, Motivation_Level, Teacher_Quality, Peer_Influence, Learning_Disabilities, Parental_Education_Level",
        "Notes",
        "Final Exam Score"
    ],

    "What to Understand": [
        "Unique identifier, not useful for trend analysis",
        "Range, average, outliers, spread",
        "Categories, frequency, class balance",
        "Requires renaming for clarity",
        "Main performance indicator"
    ]
})

print("Feature Understanding Table")
display(feature_table)

Feature Understanding Table

,Feature Type,Columns,What to Understand
0,Identifier,Student ID,"Unique identifier, not useful for trend analysis"
1,Numerical,"Age, Hours_Studied, Attendance, Assignment Sco...","Range, average, outliers, spread"
2,Categorical,"Gender, Parental_Involvement, Competency_Areas...","Categories, frequency, class balance"
3,Unclear Column,Notes,Requires renaming for clarity
4,Target Variable,Final Exam Score,Main performance indicator


### Column Descriptions

- Student ID: Unique student identifier
- Gender: Gender of the student
- Age: Student age
- Hours_Studied: Weekly study hours
- Attendance: Attendance percentage
- Assignment Score: Assignment marks
- Final Exam Score: Final examination marks
- Parental involvement: Parent participation level
- Competency Areas: Student's strength area
- Internet Access: Internet availability
- Access_to_Resources: Learning resource availability
- Extracurricular_Activities: Participation in activities
- Sleep_Hours: Daily sleep duration
- Previous_Scores: Previous academic performance
- Motivation_Level: Student motivation level
- Tutoring_Sessions: Number of tutoring sessions
- Teacher_Quality: Teacher effectiveness rating
- Peer_Influence: Influence of friends/classmates
- Physical_Activity: Physical activity level
- Learning_Disabilities: Presence of learning disabilities
- Parental_Education_Level: Parent education level
- Distance_from_Home: Distance to institution
- Notes: Miscellaneous remarks (unclear column)
### Key Points

- **Student ID** is an identifier column.
- **Final Exam Score** is the target/performance indicator.
- Factors such as study hours, attendance, previous scores, motivation level, tutoring sessions, internet access, and parental involvement may influence student performance.
### Main Performance Indicator

The primary target variable selected for analysis is **Final_Exam_Score**, as it directly reflects student academic performance.

Potential factors influencing performance include:

- Attendance
- Hours_Studied
- Assignment_Score
- Midterm_Score
- Internet_Access
- Extra_Activities
- Parental_Education_Level

##6)Missing Value Analysis

In [7]:
df.isnull().sum()

Student ID                       0
Gender                           0
Age                            477
Hours_Studied                 1903
Attendance                    1884
Assignment Score              1950
Final Exam Score                 0
Parental involvement           816
Competency Areas                 0
Internet Access                842
Access_to_Resources              0
Extracurricular_Activities       0
Sleep_Hours                   1937
Previous_Scores               1939
Motivation_Level                 0
Tutoring_Sessions             1945
Teacher_Quality                  0
Peer_Influence                   0
Physical_Activity             1943
Learning_Disabilities          828
Parental_Education_Level         0
Distance_from_Home            1963
Notes                         1478
dtype: int64

###Observation
Several columns contain missing values, while others have complete data. Missing values are present in both numerical and categorical features and will be treated during the data cleaning process.

## 7)Duplicate Row Analysis

In [8]:
df.duplicated().sum()

np.int64(300)

In [9]:
df[df.duplicated()]

,Student ID,Gender,Age,Hours_Studied,Attendance,Assignment Score,Final Exam Score,Parental involvement,Competency Areas,Internet Access,...,Previous_Scores,Motivation_Level,Tutoring_Sessions,Teacher_Quality,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Notes
5500,STU-2659,M,21.0,3.8,NaN,NaN,54,high,Data Analysis,No,...,58.0,high,11.0,Average,Neutral,8.0,Y,bachelor,17.3,-
5501,5336,male,20.0,13.2,73,36.0,89,NaN,AI,Y,...,45.0,High,8.0,Excellent,Neutral,NaN,No,High School,NaN,check
5502,STU-4153,Male,17.0,10.0,71%,40.0,63,NaN,Programming,yes,...,NaN,high,NaN,avg,positive,NaN,Yes,masters,17.0,OK
5503,656,F,23.0,6.7,NaN,NaN,84,NaN,AI,no,...,68.0,low,NaN,good,neutral,NaN,Yes,Bachelor,14.8,-
5504,3963,Female,22.0,NaN,NaN,NaN,54,high,Data Analysis,NaN,...,51.0,High,0.0,Poor,positive,2.0,Y,bachelor,12.0,OK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5795,2061,Female,21.0,6.2,59%,NaN,63,Low,Data Analysis,No,...,77.0,High,1.0,Poor,positive,1.0,no,bachelor,28.6,OK
5796,STU-2907,Male,20.0,12.3,78%,95.0,38,NaN,Web Dev,NaN,...,NaN,high,10.0,good,Negative,NaN,no,High School,26.1,-
5797,S05396,F,20.0,3.8,57%,68.0,94,medium,Cyber Security,NaN,...,87.0,High,0.0,Poor,Positive,NaN,yes,High School,22.2,NaN
5798,3369,Male,19.0,16.3,NaN,NaN,84,Medium,Web Dev,Y,...,NaN,high,10.0,Excellent,Negative,1.0,Yes,PhD,17.3,NaN
5799,S00240,Female,24.0,6.4,54,83.0,44,low,Cyber Security,no,...,NaN,high,1.0,Poor,Neutral,NaN,Yes,Bachelor,0.9,check

### Observation

A total of 300 duplicate records were identified in the dataset.

##8)Remove Duplicates

In [10]:
df = df.drop_duplicates()

In [11]:
df.duplicated().sum()

np.int64(0)

 Duplicate records can lead to biased analysis and inaccurate results. Therefore, all duplicate rows are removed before proceeding with further data cleaning and analysis.

##9)  Standardize inconsistent categorical labels

In [12]:
# All categorical columns
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts(dropna=False))

===== Student ID =====
Student ID
STU-5500    1
S00001      1
2           1
S00003      1
S00004      1
           ..
STU-17      1
16          1
15          1
STU-14      1
13          1
Name: count, Length: 5500, dtype: int64

===== Gender =====
Gender
Male      964
F         925
male      916
female    905
M         897
Female    893
Name: count, dtype: int64

===== Attendance =====
Attendance
NaN    1791
74%      53
63       51
51%      49
68       46
       ...
65       27
62%      27
84       27
57%      26
87       26
Name: count, Length: 103, dtype: int64

===== Parental involvement =====
Parental involvement
medium    832
Low       798
low       797
High      786
NaN       767
Medium    767
high      753
Name: count, dtype: int64

===== Competency Areas =====
Competency Areas
Web Dev           939
AI                932
Data Analysis     920
AI                915
Programming       898
Cyber Security    896
Name: count, dtype: int64

===== Internet Access =====
Internet Access
Yes    849
NaN    799
yes    789
N      786
no     775
No     760
Y      742
Name: count, dtype: int64

===== Access_to_Resources =====
Access_to_Resources
low       978
Low       949
med       932
Medium    910
high      891
High      840
Name: count, dtype: int64

===== Extracurricular_Activities =====
Extracurricular_Activities
Y      937
No     932
yes    920
N      910
Yes    904
no     897
Name: count, dtype: int64

===== Motivation_Level =====
Motivation_Level
High      951
low       922
Medium    921
Low       920
high      908
medium    878
Name: count, dtype: int64

===== Teacher_Quality =====
Teacher_Quality
Good         950
Average      925
Excellent    918
good         903
Poor         903
avg          901
Name: count, dtype: int64

===== Peer_Influence =====
Peer_Influence
Positive    948
Negative    937
positive    928
Neutral     924
negative    888
neutral     875
Name: count, dtype: int64

===== Learning_Disabilities =====
Learning_Disabilities
no     850
yes    841
Y      790
NaN    787
N      774
Yes    740
No     718
Name: count, dtype: int64

===== Parental_Education_Level =====
Parental_Education_Level
masters        941
PhD            930
Bachelor       919
Master         919
High School    912
bachelor       879
Name: count, dtype: int64

===== Notes =====
Notes
check    1401
OK       1391
NaN      1389
-        1319
Name: count, dtype: int64

### Observation

Several categorical columns contained inconsistent labels.

For example:
- M and Male
- F and Female
- Y and Yes

These values must be standardized to ensure consistency during analysis.

In [13]:
# Standardize Gender
df["Gender"] = df["Gender"].replace({
    "male": "Male",
    "M": "Male",
    "female": "Female",
    "F": "Female"
})

# Standardize Parental involvement
df["Parental involvement"] = df["Parental involvement"].replace({
    "high": "High",
    "medium": "Medium",
    "low": "Low"
})

# Standardize Internet Access
df["Internet Access"] = df["Internet Access"].replace({
    "yes": "Yes",
    "Y": "Yes",
    "no": "No",
    "N": "No"
})

# Standardize Access_to_Resources
df["Access_to_Resources"] = df["Access_to_Resources"].replace({
    "high": "High",
    "med": "Medium",
    "low": "Low"
})

# Standardize Extracurricular_Activities
df["Extracurricular_Activities"] = df["Extracurricular_Activities"].replace({
    "yes": "Yes",
    "Y": "Yes",
    "no": "No",
    "N": "No"
})

# Standardize Motivation_Level
df["Motivation_Level"] = df["Motivation_Level"].replace({
    "high": "High",
    "medium": "Medium",
    "low": "Low"
})

# Standardize Teacher_Quality
df["Teacher_Quality"] = df["Teacher_Quality"].replace({
    "good": "Good",
    "avg": "Average"
})

# Standardize Peer_Influence
df["Peer_Influence"] = df["Peer_Influence"].replace({
    "positive": "Positive",
    "neutral": "Neutral",
    "negative": "Negative"
})

# Standardize Learning_Disabilities
df["Learning_Disabilities"] = df["Learning_Disabilities"].replace({
    "yes": "Yes",
    "Y": "Yes",
    "no": "No",
    "N": "No"
})

# Standardize Parental_Education_Level
df["Parental_Education_Level"] = df["Parental_Education_Level"].replace({
    "bachelor": "Bachelor",
    "masters": "Master"
})

# Standardize Student Id
df["Student ID"] = [
    f"S{str(i+1).zfill(5)}"
    for i in range(len(df))
]

# Remove extra spaces from Competency Areas
df["Competency Areas"] = df["Competency Areas"].str.strip()

###Verification

In [14]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"\n===== {col} =====")
    print(df[col].value_counts(dropna=False))

===== Student ID =====
Student ID
S05500    1
S00001    1
S00002    1
S00003    1
S00004    1
         ..
S00017    1
S00016    1
S00015    1
S00014    1
S00013    1
Name: count, Length: 5500, dtype: int64

===== Gender =====
Gender
Male      2777
Female    2723
Name: count, dtype: int64

===== Attendance =====
Attendance
NaN    1791
74%      53
63       51
51%      49
68       46
       ...
65       27
62%      27
84       27
57%      26
87       26
Name: count, Length: 103, dtype: int64

===== Parental involvement =====
Parental involvement
Medium    1599
Low       1595
High      1539
NaN        767
Name: count, dtype: int64

===== Competency Areas =====
Competency Areas
AI                1847
Web Dev            939
Data Analysis      920
Programming        898
Cyber Security     896
Name: count, dtype: int64

===== Internet Access =====
Internet Access
Yes    2380
No     2321
NaN     799
Name: count, dtype: int64

===== Access_to_Resources =====
Access_to_Resources
Low       1927
Medium    1842
High      1731
Name: count, dtype: int64

===== Extracurricular_Activities =====
Extracurricular_Activities
Yes    2761
No     2739
Name: count, dtype: int64

===== Motivation_Level =====
Motivation_Level
High      1859
Low       1842
Medium    1799
Name: count, dtype: int64

===== Teacher_Quality =====
Teacher_Quality
Good         1853
Average      1826
Excellent     918
Poor          903
Name: count, dtype: int64

===== Peer_Influence =====
Peer_Influence
Positive    1876
Negative    1825
Neutral     1799
Name: count, dtype: int64

===== Learning_Disabilities =====
Learning_Disabilities
Yes    2371
No     2342
NaN     787
Name: count, dtype: int64

===== Parental_Education_Level =====
Parental_Education_Level
Master         1860
Bachelor       1798
PhD             930
High School     912
Name: count, dtype: int64

===== Notes =====
Notes
check    1401
OK       1391
NaN      1389
-        1319
Name: count, dtype: int64

##10) Rename unclear columns

In [15]:
df.rename(columns={"Notes":"Remarks"}, inplace=True)

## 11) Data Type Conversion

In [16]:
# Convert Age
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

# Convert Attendance (remove % first)
df["Attendance"] = (
    df["Attendance"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

df["Attendance"] = pd.to_numeric(df["Attendance"], errors="coerce")

# Convert other numerical columns
num_cols = [
    "Hours_Studied",
    "Assignment Score",
    "Sleep_Hours",
    "Previous_Scores",
    "Tutoring_Sessions",
    "Physical_Activity",
    "Distance_from_Home"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

### Check updated data types

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5500 entries, 0 to 5499
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student ID                  5500 non-null   object
 1   Gender                      5500 non-null   object
 2   Age                         5050 non-null   float64
 3   Hours_Studied               3699 non-null   float64
 4   Attendance                  3709 non-null   float64
 5   Assignment Score            3647 non-null   float64
 6   Final Exam Score            5500 non-null   int64
 7   Parental involvement        4733 non-null   object
 8   Competency Areas            5500 non-null   object
 9   Internet Access             4701 non-null   object
 10  Access_to_Resources         5500 non-null   object
 11  Extracurricular_Activities  5500 non-null   object
 12  Sleep_Hours                 3658 non-null   float64
 13  Previous_Scores             3652 non-null   float64
 14  Motivation_Level            5500 non-null   object
 15  Tutoring_Sessions           3659 non-null   float64
 16  Teacher_Quality             5500 non-null   object
 17  Peer_Influence              5500 non-null   object
 18  Physical_Activity           3666 non-null   float64
 19  Learning_Disabilities       4713 non-null   object
 20  Parental_Education_Level    5500 non-null   object
 21  Distance_from_Home          3635 non-null   float64
 22  Remarks                     4111 non-null   object
dtypes: float64(9), int64(1), object(13)
memory usage: 1.0+ MB

## 12) Missing Value Handling

In [18]:
# Numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values handled successfully.")

Missing values handled successfully.

In [19]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0



Missing values were successfully handled using median imputation for numerical features and mode imputation for categorical features.



After the imputation process, no missing values remained in the dataset, making it suitable for further analysis and modeling.


### Justification

Median imputation was used for numerical features because it is less affected by extreme values.

Mode imputation was used for categorical features because it preserves the most frequently occurring category.

## 13)Descriptive Statistics Table

In [20]:
df.describe()

,Age,Hours_Studied,Attendance,Assignment Score,Final Exam Score,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Distance_from_Home
count,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000,5500.000000
mean,20.891091,10.514218,74.998182,67.195636,64.797818,6.992727,66.954000,6.062727,4.963636,15.359400
std,2.243163,4.472876,12.080607,15.657253,20.536800,1.406661,15.432372,3.020731,2.572560,6.916391
min,17.000000,1.000000,50.000000,35.000000,30.000000,4.000000,35.000000,0.000000,0.000000,0.500000
25%,19.000000,8.100000,69.000000,58.000000,47.000000,6.300000,58.000000,5.000000,4.000000,11.800000
50%,21.000000,10.500000,75.000000,67.000000,64.000000,7.000000,67.000000,6.000000,5.000000,15.400000
75%,23.000000,13.000000,81.000000,75.000000,83.000000,7.700000,75.000000,8.000000,6.000000,18.900000
max,25.000000,20.000000,100.000000,100.000000,100.000000,10.000000,100.000000,12.000000,10.000000,30.000000

### Observations from Descriptive Statistics

- Student performance varies considerably across the dataset.
- Attendance levels differ among students, indicating varying engagement.
- Study hours show noticeable variation.
- Assignment and midterm scores appear to influence final performance.
- Some features contain a wide range of values, suggesting diverse academic behaviors.

## 14) Saving cleaned Dataset

In [21]:
# Save cleaned dataset
df.to_csv("2_student_performance_cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [22]:
# Preview of cleaned dataset
clean_df = pd.read_csv("2_student_performance_cleaned_dataset.csv")

clean_df.head()

,Student ID,Gender,Age,Hours_Studied,Attendance,Assignment Score,Final Exam Score,Parental involvement,Competency Areas,Internet Access,...,Previous_Scores,Motivation_Level,Tutoring_Sessions,Teacher_Quality,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Remarks
0,S00001,Male,18.0,15.6,75.0,77.0,47,Low,AI,No,...,83.0,Low,11.0,Excellent,Positive,10.0,Yes,High School,13.2,check
1,S00002,Male,21.0,7.5,75.0,36.0,85,Low,AI,No,...,67.0,Low,5.0,Good,Positive,7.0,Yes,Master,15.4,check
2,S00003,Male,20.0,8.7,68.0,64.0,98,Medium,Web Dev,Yes,...,67.0,High,6.0,Excellent,Neutral,5.0,No,High School,15.4,check
3,S00004,Male,21.0,10.5,76.0,55.0,48,Low,Data Analysis,No,...,67.0,Low,6.0,Good,Neutral,5.0,No,Bachelor,24.2,-
4,S00005,Female,17.0,10.5,75.0,73.0,50,Medium,Cyber Security,No,...,67.0,Low,6.0,Good,Neutral,4.0,Yes,Bachelor,2.9,OK

## Cleaned Dataset is successfully saved

After completing data cleaning and preprocessing, the cleaned dataset was saved as a new CSV file. This ensures that the original dataset remains unchanged and the cleaned version can be used for further analysis and modeling.


# 15) Key Observations

1. Attendance appears to have a positive impact on student performance.

2. Students who study more hours generally tend to score higher in exams.

3. The dataset originally contained missing values in Teacher_Quality, Parent_Education_Level, and Distance_from_Home.

4. A total of 300 duplicate records were identified and removed.

5. Several categorical columns contained inconsistent labels which were standardized.

6. Previous academic scores show a noticeable relationship with current exam scores.

7. The dataset contains a balanced mix of demographic, academic, and behavioral attributes.

8. The cleaned dataset is free from missing values and ready for further analysis.

### Analytical Questions

1. Do students with higher attendance tend to score better?

2. Is there a visible relationship between study hours and final marks?

3. Are some categories underrepresented?

4. Do students participating in extra activities show any trend in performance?

These questions can be explored further during Exploratory Data Analysis (EDA) and visualization tasks in further tasks.